version: '3'

services:
  front:
    extends:
      file: ./front/docker-compose.yml
      service: app
  
  back:
    extends:
      file: ./back/docker-compose.yml
      service: app
    depends_on:
      db:
        condition: service_healthy

  db:
    extends:
      file: ./back/docker-compose.yml
      service: db
