version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:v1
    ports:
      - "8000:8000"
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "bebeparaceiro"
      DB_HOST: "db"
      DB_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bebeparceiro
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5